/* Copyright (c) 2013 Brivium (http://brivium.com)
 * Author: Brivium
 * Addon: ModernStatistic
 * Version: 1.7.0
 * Released under the Brivium License Agreement: http://brivium.com/pages/terms-of-use
 */

$brmsCusLayout=$brmsCusItemLimit=$brmsUseLocationHash=$brmsPreview=$brmsActive=!1;$brmsHardReload=0;
function brmsGetStatistic(b,a){a||(a=$("#brmsEntryLimit").val());($loadUrl=$("#brmsNav").data("loadUrl")?$("#brmsNav").data("loadUrl"):$("#brmsNav").attr("data-loadUrl"))||($loadUrl="brivium-modern-statistic/statistics.json");XenForo.ajax($loadUrl,{tab_id:b,hard_reload:$brmsHardReload,limit:a},function(a){if(!1!==XenForo.hasResponseError(a))return!0;$(".brmsVerticalTabs .itemCounnew").remove();if(a.tabContentHtml){if($("#brmsTabContent_"+b).html(a.tabContentHtml),$numberNew=$("#brmsTabContent_0").find(".new_cm_item").length)$itemCouter=
'<strong class="itemCounnew" ><span class="Total">'+$numberNew+'</span><span class="arrow"></span></strong>',$("#modernStats_lastThread_tabs").prepend($itemCouter)}else $("#brmsTabContent_"+b).html("");a.limit&&$("#brmsEntryLimit").val(a.limit);XenForo.register(".Popup","XenForo.PopupMenu","XenForoActivatePopups");XenForo.register("a.OverlayTrigger, input.OverlayTrigger, button.OverlayTrigger, label.OverlayTrigger, a.username, a.avatar","XenForo.OverlayTrigger");$("#brmsRefresh").removeClass("disable");
brmsResponsiveInit();XenForo.activate(document)},{cache:!1})}function brmsShowTab(b){b?$("#brmsNav ul.brmsTabNav > li > a[data-content='"+b+"']").click():$("#brmsNav ul.brmsTabNav > li.current a").click()}function brmsRunInterval(){console.log("Mordern Statistic Update "+$brmsInterval+"s");brmsGetStatistic($("#brmsNav ul.brmsTabNav > li.current a").data("tabid"),$("#brmsEntryLimit").val())}
function brmsUpdateInterval(){if(!$brmsActive&&($brmsInterval=$("#brmsInterval").val(),0<$brmsInterval))return $brmsActive=window.setInterval(brmsRunInterval,1E3*$brmsInterval)}function brmsClearInterval(){window.clearInterval($brmsActive);$brmsActive=!1;return $brmsInterval=0}function brmsResetInterval(){brmsClearInterval();brmsUpdateInterval()}
function brmsInit(){$brmsCusLayout&&$.cookie("brmsLayoutChange")&&($("#brmsNav").hasClass($.cookie("brmsLayoutChange"))||$("#brmsNav").attr("class",$.cookie("brmsLayoutChange")));$brmsCusItemLimit&&$.cookie("brmsNumberEntry")&&$("#brmsEntryLimit").val($.cookie("brmsNumberEntry"));$numberNav=$("#brmsNav ul.brmsTabNav > li").length-2;$("#brmsNav ul.brmsTabNav > li:first").addClass("first");$("#brmsNav ul.brmsTabNav > li:eq("+$numberNav+")").addClass("last")}
function brmsResponsiveInit(){$("#brmsNav").hasClass("brmsTopTabs")?($tabNavWidth=0,$calWidth=$(".brmsStatisticCtrl").width()-$(".brmsCtrl").width()-75,$showHiddenMenu=!1,$(".brmsTabNav > li.brmlShow").each(function(){$tabNavWidth+$(this).width()<=$calWidth?($tabNavWidth+=$(this).width(),$(this).css({display:"block"}),$(".brmsTabNavHidden li:eq("+$(this).index()+")").css({display:"none"})):($showHiddenMenu=!0,$(this).css({display:"none"}),$(".brmsTabNavHidden li:eq("+$(this).index()+")").css({display:"block"}))}),
$showHiddenMenu?$(".brmsTabNavHiddenMenu").show():$(".brmsTabNavHiddenMenu").hide(),480<$("#brmsNav").width()?($.cookie("brmsLayoutChange")&&!$("#brmsNav").hasClass($.cookie("brmsLayoutChange"))&&$("#brmsNav").attr("class",$.cookie("brmsLayoutChange")),$(".brmsLayoutList").css({display:"inline-block"})):$(".brmsLayoutList").css({display:"none"})):480>=$("#brmsNav").width()&&($("#brmsNav").attr("class","brmsTopTabs"),$(".brmsLayoutList").css({display:"none"}));$itemContent=$("#brmsNav .brmsTabContent ol li .itemContent");
550>$(".brmsTabContent.current").width()?($itemContent.find(".itemDetail").hide(),$itemContent.find(".itemTitle").css({"max-width":"90%"}),350>$(".brmsTabContent.current").width()?$itemContent.find(".prefix").hide():$itemContent.find(".prefix").show()):($itemContent.find(".prefix").show(),$itemContent.find(".itemDetail").show(),$itemContent.find(".itemTitle").css({width:"auto"}))}
$(document).ready(function(){brmsInit();$(function(){$("#brmsNav ul.brmsTabNav > li > a, #brmsNav .brmsTabNavHidden  ul.brmsDropdownMenu  > li > a").click(function(){$(this).closest("li").hasClass("current")||($content=$(this).data("content"),$("#"+$content).find(".brmsIcoLoader ").length&&brmsGetStatistic($(this).data("tabid"),0),$("#brmsNav ul.brmsTabNav > li , #brmsNav .brmsTabNavHidden  ul.brmsDropdownMenu  > li").removeClass("current"),$(this).closest("li").addClass("current"),$brmsUseLocationHash&&
(window.location.hash=$content.replace("brmsTabContent_","brmsTab")),$("#brmsNav .brmsTabContent").hide(),$(".brmsTabContent").removeClass("current"),$("#"+$content).fadeIn(100).addClass("current"),brmsResponsiveInit())});location.hash&&$brmsUseLocationHash?brmsShowTab(location.hash.replace("#brmsTab","brmsTabContent_")):brmsShowTab($(".brmsTabContent:first").attr("id"));brmsUpdateInterval()});if("custom_preview"==$brmsPreview){var b=$("#brmsToolTip");$(".itemstast").live("mouseover",function(){var a=
$(this).find(".itemTitle").find("a");b.html(toolTips(a)).show().insertBefore(a)});$(".itemstast").live("mouseout",function(){b.empty().hide()})}$(".brmsNumberEntry").click(function(a){$(this).data("limit")&&($("#brmsEntryLimit").val($(this).data("limit")),$.cookie("brmsNumberEntry",$(this).data("limit")),brmsResetInterval(),$brmsHardReload=1,brmsRunInterval(),$brmsHardReload=!1);a.preventDefault()});$(".brmsLayoutChange").click(function(a){$(this).data("layout")&&($("#brmsNav").hasClass($(this).data("layout"))||
$("#brmsNav").attr("class",$(this).data("layout")),$.cookie("brmsLayoutChange",$(this).data("layout")),brmsResponsiveInit());a.preventDefault()});$("#brmsRefresh").click(function(a){$(this).hasClass("disable")||(brmsResetInterval(),$brmsHardReload=1,brmsRunInterval(),$brmsHardReload=!1,$(this).addClass("disable"));a.preventDefault()});brmsResponsiveInit();$(window).resize(function(){brmsResponsiveInit()});$(".brmsDropdownToggle").hover(function(a){$drMenu=$(this).find("ul.brmsDropdownMenu");$drMenu.show();
$drMenu.offset().left+$drMenu.width()>$("#brmsNav").width()?$drMenu.addClass("edge"):$drMenu.removeClass("edge");"none"!=$drMenu.css("display")&&0>=$drMenu.offset().left&&$drMenu.css({left:0})},function(a){$(this).find("ul.brmsDropdownMenu").hide();$drMenu.offset().left+$drMenu.width()>$("#brmsNav").width()?$drMenu.addClass("edge"):$drMenu.removeClass("edge");"none"!=$drMenu.css("display")&&0>=$drMenu.offset().left&&$drMenu.css({left:0})});$(".brmsDropdownToggle").click(function(a){$(this).find("ul.brmsDropdownMenu").toggle()})});